### PR TITLE
Added D3D12Renderer and an Event class (like in C#)

### PR DESCRIPTION
**Pull request by CXCubeHD**
the hooking logic and rendering logic needs to be done.

### CODE REVIEW

**Review by DisabledMallis — COMMENTED** [review]
Whats the idea with the Event thing? I assume for handling hooks better when theyre called? Stuff like PlayerMoveEvent or something?

**Review by DisabledMallis — CHANGES_REQUESTED** [review]
The renderer(s) should not have any hooking code. That should be left up to the patches. Kiero also can take care of this. I can make a patch for the dx12 swap chain using kiero for you if you need.

**Comment by CXCubeHD** [comment]
the event function is just like in C# the events (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event)
Basically a subscriber can be registered with event += (function) which will be called on every render frame

the hook functions are a wrapper for kiero hooking. It also checks if it already is hooking the vtablefunctions.
Basically the D3D1* Renderer wraps hooking and handles all the directx stuff. It works in every version of Minecraft and doesn't need to be updated with every new version

**Comment by DisabledMallis** [comment]
> the event function is just like in C# the events ([docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event))
> Basically a subscriber can be registered with event += (function) which will be called on every render frame
> 
> the hook functions are a wrapper for kiero hooking. It also checks if it already is hooking the vtablefunctions.
> Basically the D3D1* Renderer wraps hooking and handles all the directx stuff. It works in every version of Minecraft and doesn't need to be updated with every new version

1. I like the event idea, should expand on it for use with hooks as well (if it can't be used for that, but by the looks of it, it seems like it can) Good work.
2. Patches should handle any hooking/modifying of any code/binary at runtime. All hooks, assembly edits, etc should be a patch. This includes DX hooking. This is important, because if a patch fails, it can automatically be safely handled (most of the time) meaning less crashing.

Focus on making your work fit with #2. Remember there is a Dx11 and ImGui branch that uses kiero to mostly do that. Use it!!

**Comment by CXCubeHD** [comment]
gonna make another pull request sometimes later

**Comment by DisabledMallis** [comment]
Just modify this one??

**Pull request closed without merging**
